### ISSUE TITLE
Invoking emacs `ispell` as first part of Hammerspoon handling

### ISSUE THREAD

**Issue by jeremyf** [dmgerman/editWithEmacs.spoon#1]
https://github.com/dmgerman/editWithEmacs.spoon/blob/52ecaf193c4034707170624abeb3f355e85fa391/init.lua#L45

What command are you looking to invoke with this key combination?  For me, this invoked `ispell`.  When I changed  it to `hs.eventtap.keyStroke({"alt"}, "x")` the functionality appeared to work as intended.

I also checked the default emacs (e.g., `emacs -q`) and typed <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>;</kbd> which also invoked `ispell`.

**Comment by dmgerman** [comment]
Oops. It is probably prelude that binds that. Meta-x. I should have sued that instad.
